					<section class="copyright">
						<div>$page.properties.("project.name")$ is Open Source and available under the <a href="http://creativecommons.org/publicdomain/zero/1.0/">CC0 License</a>.</div>
						<p class="legal">
							&copy; 2011-$page.properties.("date.year")$ <a href="https://www.lightbend.com" target="_blank">Lightbend, Inc.</a> |
							<a href="https://www.lightbend.com/legal/licenses" target="_blank">Licenses</a> |
							<a href="https://www.lightbend.com/legal/terms" target="_blank">Terms</a> |
							<a href="https://www.lightbend.com/legal/privacy" target="_blank">Privacy Policy</a> |
							<a href="https://akka.io/cookie/" target="_blank">Cookie Listing</a> |
							<a class="optanon-toggle-display">Cookie Settings</a>
						</p>
					</section>
