name: Compile

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  documentation:
    name: Documentation with Paradox
    runs-on: ubuntu-22.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.17

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: "Create site with Paradox"
        run: cd docs && sbt makeSite

#      - name: Run Link Validator
#        run: cs launch net.runne::site-link-validator:0.2.2 -- scripts/link-validator.conf

  samples:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - { directory: ftp-to-file }
          - { directory: http-csv-to-kafka }
          - { directory: jdbc-to-elasticsearch }
          - { directory: jms }
          - { directory: kafka-to-websocket-clients }
          - { directory: kafka-to-elasticsearch }
          - { directory: mqtt-to-kafka }
          - { directory: file-to-elasticsearch }
          - { directory: mqtt-http-to-s3-java }
          - { directory: sqs-java }
          - { directory: rotate-logs-to-ftp }

    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: ${{ matrix.directory }}
        env:
          DIRECTORY: ${{ matrix.directory }}
        run: cd alpakka-sample-${DIRECTORY} && sbt compile
